### PR TITLE
Game version, home page, fixes, improvements

### LINKED ISSUE #2: Question: Will game version be included in api?
I noticed right now the api doesn't give a compatible game version. I am trying to make an alternative launcher, but its hard to support multiple versions without a version in the api. Thus my question will it be implemented in the future?

### LINKED ISSUE #13: Add a link to a mod installer.
Add a link to either of the Mod Installers in the sidebar, or maybe a more prominent button somewhere else.

Beat Saber Mod Manager
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases/latest

Beat Drop
https://github.com/StarGazer1258/BeatDrop/releases/latest

### LINKED ISSUE #14: Add a landing page for Beat Mods with basic info.
When users visit https://beatmods.com they are immediately forwarded to https://beatmods.com/#/mods and shown the list of mods with no instructions on how to install them.

https://beatmods.com/ should really have a landing page with basic install instructions and useful links.

Really basic example
```
**Beat Mods**

This is a mod repository for Beat Saber!

If you need help installing mods, visit
https://bsmg.wiki/beginners-guide
```

### PR DESCRIPTION
**Pull request by raftario**
**I did test it as much as possible but some more testing wouldn't hurt.**
## Game version
Game versions are now included in the API.
* Access via the `gameVersion` key of the mod object.
* Sort using the `gameversion` URI query (`gameVersion` also works). If not specified, returns mods with any game version.
* Fully implemented in the mod creation and update UIs.
* Displayed in the mod list page.
* Missing game version replaced by `"unspecified"`.
* Available game versions accessible at `/api/v1/version`.
### Todo
* Sort by game version in the mod list page.
## Home page
Actual homepage.
* Visitors are not redirected to the mod list page anymore.
* Links to the beginner's guide, Discord and mod installers.
* Can be accessed via the side menu.
### Todo
* Add link to ModAssistant once it's ready for production
## Fixes and improvements
* Added missing space in copyright notice.
* Sorting doesn't do weird stuff for admins.
* Map mod categories instead of listing them every time.
## Settings page
Settings page to edit game version, mod categories (and upload limit ?).
* Available in the sidebar for admins.
* Doesn't display for members.
### Todo
As of right now the settings page doesn't work. Game versions and mod categories are editable in `src/config/lists.js`.
* Finish the UI.
* All the backend / DB stuff.

Closes #2 
Closes #13 
Closes #14

### CODE REVIEW

File: src/client/app/views/home/index.tsx [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import React, { Component } from "react";
+import { Container } from "reactstrap";
+
+export default class ModList extends Component<{ history: any; user: any | null }> {
```
Comment (PlasmaPower) [inline src/client/app/views/home/index.tsx]: This should probably be called Home or something instead of ModList. I'm assuming that's just from copy-paste.

**Review by PlasmaPower — COMMENTED** [review]
Other than that, LGTM. I'll look over the settings code once that's done.

File: src/client/app/views/home/index.tsx (hunk 1 above)
Comment (raftario) [reply src/client/app/views/home/index.tsx]: Oof. You got me there. Gonna change that with the other small fixes.

**Comment by raftario** [comment]
Just fixed the last bits and added `/api/v1/version`, should be ready for merging.

**Review by williums — APPROVED** [review]
LGTM
